image: node

stages:
  - build
  - test

variables:
    CLI_VERSION: 4.4.1
    IMAGE: hello-spa:latest
  
test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
  - ng test --progress false --watch false
  
build-image:
  stage: build
  image: docker
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE