stages:
  - build
  - test

variables:
  CLI_VERSION: 9.1.5
  REPOSITORY_URL: 439352748066.dkr.ecr.eu-central-1.amazonaws.com/hello-spa
  
test:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  script:
  - npm install
  - ng test --progress false --watch false
  
build-image:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
  script:
    - $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
  tags:
    - docker